server:
  port: 9000

spring:
  application:
    name: weather-client


feign:
  hystrix:
    enabled: true   # 开启Feign的hystrix支持

eureka:
  instance:
    lease-expiration-duration-in-seconds: 3  #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除,默认90s
    lease-renewal-interval-in-seconds: 1     #服务刷新时间配置，每隔这个时间会主动心跳一次,默认30s
    prefer-ip-address: true                  #是否使用ip注册到eureka,默认主机名,注意多网卡,内外ip不一致情况.
  client:
    service-url:
      defaultZone: http://47.75.103.223:5673/eureka  #指定eureka的地址
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

