server:
  port: 9001

spring:
  application:
    name: city-data

eureka:
  instance:
    prefer-ip-address: true           #注册时使用ip而不是主机名
    ip-address: xxx.xx.xx.xxx         #手动指定本实例的ip(内网ip与外网ip不一致,或者存在多块网卡的时候使用)
  client:
    service-url:
      defaultZone: http://xxx.xx.xx.xxx:5673/eureka
